import type { NextPage } from 'next';
import Head from 'next/head';
import HomePage from '../components/home/HomePage';
import GetData from '../helpers/functions';
import { useEffect } from 'react';

const url = 'https://my-json-server.typicode.com/mosgizy/portfolio-api-V2/db';

const Home: NextPage = () => {
	const data = GetData(url);
	useEffect(() => {
		console.log(data);
	}, []);

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<HomePage />
		</div>
	);
};

export default Home;
